version: 1.0.{build}
branches:
  only:
  - master
image: WMF 5
install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    Install-Module Pester
    Copy-Item -Path ./psaws -Destination "C:\Program Files\WindowsPowerShell\Modules\psaws" -Recurse
build: off
test_script:
- ps: Invoke-Pester ./tests/psaws.tests.ps1