version: 1.0.{build}
branches:
  only:
  - master
image: WMF 5
environment:
  psgallery_apiKey:
    secure: QvpliMcd1+3wTCfqfwCJIDSLW8l3ejGWqjPRnLYKjc2TrFv6pKLAnHjPhKS4Ktbk
install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force

    Install-Module AwsPowerShell -Force

    Install-Module Pester -Force

    Copy-Item -Path ./psaws -Destination "C:\Program Files\WindowsPowerShell\Modules\psaws" -Recurse
build: off
test_script:
- ps: >-
        $testResultsFile = ".\TestsResults.xml"

        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru

        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))

        if ($res.FailedCount -gt 0) { 

            throw "$($res.FailedCount) tests failed."

        }
deploy_script:

- ps: if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -eq '#deploy') {Publish-Module -Name psaws -NuGetApiKey $env:psgallery_apiKey -Verbose}